<!doctype html>
<html lang="{{ $locale }}" dir="{{ $locale === 'ar' ? 'rtl' : 'ltr' }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $page->seo('title') }}</title>
    <meta name="description" content="{{ $page->seo('description') }}">
    <meta name="keywords" content="{{ $page->seo('keywords') }}">
    <meta name="robots" content="{{ ($page->seo['indexable'] ?? true) ? 'index,follow' : 'noindex,nofollow' }}">
    <link rel="canonical" href="{{ $locale === 'ar' ? route('home.ar') : route('home.en') }}">
    <link rel="alternate" hreflang="ar" href="{{ route('home.ar') }}">
    <link rel="alternate" hreflang="en" href="{{ route('home.en') }}">
    <link rel="alternate" hreflang="x-default" href="{{ route('home.ar') }}">
    <meta property="og:type" content="website"><meta property="og:locale" content="{{ $locale === 'ar' ? 'ar_SA' : 'en_US' }}">
    <meta property="og:title" content="{{ $page->seo('og_title') }}"><meta property="og:description" content="{{ $page->seo('og_description') }}">
    <meta property="og:url" content="{{ $locale === 'ar' ? route('home.ar') : route('home.en') }}"><meta property="og:image" content="{{ $page->media($page->seo['og_image'] ?? $page->get('brand.logo')) }}">
    <meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{{ $page->seo('og_title') }}"><meta name="twitter:description" content="{{ $page->seo('og_description') }}">
    <style>:root{@foreach($page->theme as $key=>$value)--{{ str_replace('_','-',$key) }}:{{ $value }};@endforeach}</style>
    @vite(['resources/css/site.css', 'resources/js/site.js'])
    @php
        $l = fn($value) => is_array($value) ? ($value[$locale] ?? $value['ar'] ?? reset($value)) : $value;
        $schema = ['@context'=>'https://schema.org','@type'=>['Person','ProfessionalService'],'name'=>$page->trans('brand.name'),'jobTitle'=>$page->seo['schema']['job_title'][$locale] ?? '', 'areaServed'=>$page->seo['schema']['service_area'] ?? 'Saudi Arabia','url'=>$locale === 'ar' ? route('home.ar') : route('home.en')];
    @endphp
    <script type="application/ld+json">{!! json_encode($schema, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) !!}</script>
</head>
<body>
@if(!empty($isPreview))<div class="preview-banner">{{ $locale === 'ar' ? 'أنت تشاهد نسخة المعاينة' : 'You are viewing a preview' }}</div>@endif
<div class="loader" id="loader" aria-hidden="true"><div class="loader-mark"></div></div>
<div class="progress-bar" id="progress"></div>
<div class="site-shell">
    <nav class="nav">
        <a class="brand" href="#top" aria-label="{{ $page->trans('brand.name') }}"><span class="brand-mark"><img src="{{ $page->media($page->get('brand.logo')) }}" alt="{{ $page->trans('brand.name') }}"></span><span>{{ $page->trans('brand.name') }}</span></a>
        <button class="nav-toggle" type="button" aria-label="Menu" aria-expanded="false"><i class="fa-solid fa-bars"></i></button>
        <div class="nav-links" aria-label="Navigation">
            @foreach($page->items('navigation') as $item)<a href="#{{ $item['anchor'] }}">{{ $l($item['label']) }}</a>@endforeach
            <a href="{{ $locale === 'ar' ? route('home.en') : route('home.ar') }}" aria-label="Language">{{ $locale === 'ar' ? 'EN' : 'العربية' }}</a>
        </div>
    </nav>

    <header class="hero" id="top">
        <canvas id="hero-web" aria-hidden="true"></canvas>
        <div class="hero-kinetic-words" aria-hidden="true">
            @foreach($page->get('hero.words', []) as $index => $word)
                @php($positions=[['11%','7%'],['18%','28%'],['13%','68%'],['34%','5%'],['45%','18%'],['33%','43%'],['38%','76%'],['62%','8%'],['69%','31%'],['58%','60%'],['77%','73%'],['82%','15%'],['24%','86%'],['86%','48%']])
                <span class="kinetic-word" data-depth="{{ 30 + (($index * 7) % 45) }}" data-spin="{{ $index % 2 ? -5 : 5 }}" style="--top:{{ $positions[$index][0] ?? '50%' }};--right:{{ $positions[$index][1] ?? '50%' }};--size:{{ .88 + (($index % 4) * .09) }}rem;--delay:-{{ $index * .7 }}s;--duration:{{ 12 + ($index % 5) }}s;--drift-x:{{ $index % 2 ? 40 : -44 }}px;--drift-y:{{ $index % 3 ? 28 : -28 }}px;--drop-y:20px;--tilt:{{ $index % 2 ? 7 : -7 }}deg;--tilt-mid:{{ $index % 2 ? -5 : 5 }}deg"><span class="kinetic-word-label">{{ $word }}</span></span>
            @endforeach
        </div>
        <div class="hero-grid">
            <div class="hero-copybox reveal"><span class="eyebrow"><i class="fa-solid fa-wand-magic-sparkles"></i> {{ $page->trans('hero.eyebrow') }}</span><h1>{{ $page->trans('hero.title') }}</h1><p class="hero-copy">{{ $page->trans('hero.description') }}</p><div class="hero-actions"><a class="btn" href="#work"><i class="fa-solid fa-border-all"></i> {{ $page->trans('hero.primary_button') }}</a><a class="btn secondary" href="#freebies"><i class="fa-solid fa-download"></i> {{ $page->trans('hero.secondary_button') }}</a></div></div>
            <div class="hero-board reveal" aria-hidden="true"><div class="showcase-stack floaty"><figure class="hero-card big"><img src="{{ $page->media($page->get('hero.feature_image')) }}" alt=""></figure><figure class="hero-card small"><img src="{{ $page->media($page->get('hero.secondary_image')) }}" alt=""></figure><div class="hero-card metric"><div class="metric-grid">@foreach(array_slice($page->items('stats'),0,4) as $stat)<div class="metric-item"><strong>{{ $stat['value'] }}{{ $stat['suffix'] }}</strong><span>{{ $l($stat['label']) }}</span></div>@endforeach</div></div></div></div>
        </div>
    </header>

    <section class="marketing-platforms" aria-label="Marketing platforms"><div class="platform-strip reveal">@foreach($page->items('platforms') as $platform)<a class="platform-logo" href="{{ $platform['url'] }}" target="_blank" rel="noopener"><span class="platform-mark"><i class="{{ $platform['icon'] }}"></i></span><span class="platform-copy"><strong>{{ $platform['name'] }}</strong></span></a>@endforeach</div></section>
    <section class="impact-stats" aria-label="Statistics"><div class="impact-stats-inner reveal">@foreach($page->items('stats') as $stat)<article class="impact-stat"><span class="impact-stat-icon"><i class="{{ $stat['icon'] }}"></i></span><div class="impact-stat-value"><strong data-stat-target="{{ $stat['value'] }}">{{ $stat['value'] }}</strong><small>{{ $stat['suffix'] }}</small></div><p>{{ $l($stat['label']) }}</p></article>@endforeach</div></section>

    @if($page->get('headings.services.visible', true))<section class="content-section" id="services"><div class="section-inner"><x-site.section-head :data="$page->get('headings.services')" :locale="$locale"/><div class="service-grid">@foreach($page->items('services') as $service)<article class="service-card reveal"><span class="icon"><i class="{{ $service['icon'] }}"></i></span><h3>{{ $l($service['title']) }}</h3><p>{{ $l($service['description']) }}</p></article>@endforeach</div></div></section>@endif

    @if($page->get('headings.work.visible', true))<section class="content-section" id="work"><div class="section-inner"><x-site.section-head :data="$page->get('headings.work')" :locale="$locale"/><div class="results-cases">@foreach($page->items('cases') as $case)<article class="result-case reveal"><div class="result-case-head"><div><h3>{{ $l($case['title']) }}</h3><p>{{ $l($case['subtitle']) }}</p></div><span class="result-case-badge">{{ $case['badge'] }}</span></div><div class="result-case-metrics">@foreach($case['metrics'] as $metric)<div><strong>{{ $l($metric['value']) }}</strong><span>{{ $l($metric['label']) }}</span></div>@endforeach</div><div class="result-case-tags">@foreach($case['tags'] as $tag)<span>{{ $tag }}</span>@endforeach</div><div class="result-case-gallery {{ count($case['images']) === 1 ? 'result-case-gallery-single' : 'result-case-gallery-featured' }}">@foreach($case['images'] as $image)<button class="result-case-media {{ $loop->first ? 'result-case-media-featured' : '' }}" type="button"><img src="{{ $page->media($image) }}" alt="{{ $l($case['title']) }}" loading="lazy"></button>@endforeach</div></article>@endforeach</div></div></section>@endif

    @php($stores=$page->items('stores'))
    @if($page->get('headings.stores.visible', true) && count($stores))<section class="content-section" id="stores"><div class="section-inner"><x-site.section-head :data="$page->get('headings.stores')" :locale="$locale"/><div class="store-lab reveal" data-store-lab><article class="store-lab-details"><div><span class="store-index" data-store-index>01 / {{ str_pad(count($stores),2,'0',STR_PAD_LEFT) }}</span><span class="kicker" data-store-category>{{ $l($stores[0]['category']) }}</span><h3 data-store-title>{{ $l($stores[0]['title']) }}</h3><p data-store-description>{{ $l($stores[0]['description']) }}</p><div class="store-chips" data-store-chips>@foreach($stores[0]['chips'] as $chip)<span>{{ $chip }}</span>@endforeach</div></div><a class="btn secondary" href="#contact"><i class="fa-solid fa-paper-plane"></i> {{ $locale === 'ar' ? 'ابدأ متجر مشابه' : 'Start a similar store' }}</a></article><figure class="store-browser store-main-media"><div class="store-browser-bar"><span class="store-window-dots"><span></span><span></span><span></span></span><span class="store-url" data-store-url>{{ $stores[0]['url_label'] }}</span><i class="fa-solid fa-up-right-and-down-left-from-center"></i></div><div class="store-screen" data-store-screen><img src="{{ $page->media($stores[0]['image']) }}" alt="{{ $l($stores[0]['title']) }}" data-store-image></div></figure><div class="store-selector">@foreach($stores as $store)<button class="store-pick {{ $loop->first ? 'is-active' : '' }}" type="button" data-store-pick data-src="{{ $page->media($store['image']) }}" data-title="{{ $l($store['title']) }}" data-category="{{ $l($store['category']) }}" data-description="{{ $l($store['description']) }}" data-url="{{ $store['url_label'] }}" data-chips="{{ implode('|',$store['chips']) }}"><img src="{{ $page->media($store['image']) }}" alt=""><strong>{{ $l($store['title']) }}</strong><span>{{ $l($store['category']) }}</span></button>@endforeach</div></div></div></section>@endif

    @if($page->get('headings.social.visible', true))<section class="content-section" id="social"><div class="section-inner"><x-site.section-head :data="$page->get('headings.social')" :locale="$locale"/><div class="gallery-shell social-slider reveal"><button class="gallery-nav prev" type="button" aria-label="Previous"><i class="fa-solid fa-chevron-right"></i></button><div class="gallery-track" tabindex="0">@foreach($page->items('social') as $item)<figure class="social-slide"><img src="{{ $page->media($item['image']) }}" alt="{{ $l($item['alt']) }}" loading="lazy"></figure>@endforeach</div><button class="gallery-nav next" type="button" aria-label="Next"><i class="fa-solid fa-chevron-left"></i></button></div></div></section>@endif

    @if($page->get('headings.clients.visible', true))<section class="content-section" id="clients"><div class="section-inner"><x-site.section-head :data="$page->get('headings.clients')" :locale="$locale"/><div class="split-grid"><div class="testimonials-grid">@foreach($page->items('testimonials') as $item)<figure class="testimonial-card reveal"><img src="{{ $page->media($item['image']) }}" alt="{{ $l($item['alt']) }}" loading="lazy"></figure>@endforeach</div><div class="audio-list">@foreach($page->items('audio') as $audio)<article class="audio-card reveal"><div class="audio-title"><i class="fa-solid fa-volume-high"></i> {{ $l($audio['title']) }}</div><audio controls preload="none" src="{{ $page->media($audio['file']) }}"></audio></article>@endforeach</div></div></div></section>@endif

    @if($page->get('headings.logos.visible', true))<section class="content-section" id="logos"><div class="section-inner"><x-site.section-head :data="$page->get('headings.logos')" :locale="$locale"/></div><div class="logo-band reveal"><div class="logo-grid">@foreach($page->items('logos') as $logo)<span class="logo-item"><img src="{{ $page->media($logo['image']) }}" alt="{{ $l($logo['alt']) }}" loading="lazy"></span>@endforeach</div></div></section>@endif

    @if($page->get('headings.freebies.visible', true))<section class="content-section" id="freebies"><div class="section-inner"><x-site.section-head :data="$page->get('headings.freebies')" :locale="$locale"/><div class="freebies-panel"><article class="newsletter-card reveal"><div class="newsletter-head"><span class="download-icon"><i class="fa-solid fa-envelope-open-text"></i></span><div><h3>{{ $page->trans('newsletter.title') }}</h3><p>{{ $page->trans('newsletter.description') }}</p></div></div><form class="newsletter-form" action="{{ route('subscribers.store') }}" novalidate>@csrf<input type="hidden" name="locale" value="{{ $locale }}"><input type="hidden" name="form_started" value="{{ now()->timestamp }}"><input class="hp-field" name="website" tabindex="-1" autocomplete="off"><div class="form-message" role="status"><i class="fa-solid fa-check"></i><span><strong></strong></span></div><div class="field"><label for="newsletter-email">{{ $locale === 'ar' ? 'البريد الإلكتروني' : 'Email address' }}</label><input id="newsletter-email" name="email" type="email" placeholder="name@example.com" required data-email-guard="true"><span class="field-error"></span></div><button class="btn" type="submit"><i class="fa-solid fa-envelope"></i> {{ $page->trans('newsletter.button') }}</button></form><div class="newsletter-files">@foreach($page->items('freebies') as $resource)<span><i class="{{ $resource['icon'] }}"></i> {{ $l($resource['title']) }}</span>@endforeach</div></article></div></div></section>@endif

    <section class="content-section" id="contact"><div class="section-inner"><div class="contact-panel reveal"><div class="contact-note"><div><span class="kicker">{{ $page->trans('contact.kicker') }}</span><h2>{{ $page->trans('contact.title') }}</h2><p>{{ $page->trans('contact.description') }}</p></div><div class="hero-actions"><a class="btn" href="#top"><i class="fa-solid fa-arrow-up"></i> {{ $locale === 'ar' ? 'العودة للأعلى' : 'Back to top' }}</a></div></div><form class="project-form" action="{{ route('contact.store') }}" novalidate>@csrf<input type="hidden" name="locale" value="{{ $locale }}"><input type="hidden" name="form_started" value="{{ now()->timestamp }}"><input class="hp-field" name="website" tabindex="-1" autocomplete="off"><div class="form-message" role="status"><i class="fa-solid fa-check"></i><span><strong></strong></span></div><div class="field"><label for="client-name">{{ $locale === 'ar' ? 'الاسم الكامل' : 'Full name' }}</label><input id="client-name" name="name" type="text" required minlength="3"><span class="field-error"></span></div><div class="field"><label for="client-email">{{ $locale === 'ar' ? 'البريد الإلكتروني' : 'Email address' }}</label><input id="client-email" name="email" type="email" required><span class="field-error"></span></div><div class="field"><label for="consultation-date">{{ $locale === 'ar' ? 'موعد الاستشارة المقترح' : 'Preferred consultation date' }}</label><input id="consultation-date" name="consultation_date" type="date"><span class="field-error"></span></div><div class="field"><label for="service-type">{{ $locale === 'ar' ? 'نوع الخدمة' : 'Service' }}</label><select id="service-type" name="service" required><option value="">{{ $locale === 'ar' ? 'اختر الخدمة' : 'Choose a service' }}</option>@foreach($page->get('contact.services',[]) as $service)<option>{{ $l($service) }}</option>@endforeach</select><span class="field-error"></span></div><div class="field"><label for="project-details">{{ $locale === 'ar' ? 'نبذة عن المشروع' : 'Project brief' }}</label><textarea id="project-details" name="message" required minlength="12"></textarea><span class="field-error"></span></div><button class="btn" type="submit"><i class="fa-solid fa-paper-plane"></i> {{ $page->trans('contact.button') }}</button></form></div></div></section>
</div>
<div class="lightbox" id="image-lightbox" aria-hidden="true"><button class="lightbox-close" type="button" aria-label="Close"><i class="fa-solid fa-xmark"></i></button><img src="" alt=""></div>
</body></html>
