<?php

$t = static fn (string $ar, string $en): array => ['ar' => $ar, 'en' => $en];
$media = static fn (string $path): string => 'media/source/'.$path;

return [
    'content' => [
        'brand' => [
            'name' => $t('أمل العيسى', 'Amal Aleissa'),
            'logo' => $media('logo.webp'),
        ],
        'navigation' => [
            ['label' => $t('لماذا أمل؟', 'Why Amal'), 'anchor' => 'why', 'order' => 1, 'visible' => true],
            ['label' => $t('نتائج الأعمال', 'Results'), 'anchor' => 'work', 'order' => 2, 'visible' => true],
            ['label' => $t('المتاجر', 'Stores'), 'anchor' => 'stores', 'order' => 3, 'visible' => true],
            ['label' => $t('السوشال ميديا', 'Social'), 'anchor' => 'social', 'order' => 4, 'visible' => true],
            ['label' => $t('الخدمات', 'Services'), 'anchor' => 'services', 'order' => 5, 'visible' => true],
            ['label' => $t('موارد مجانية', 'Resources'), 'anchor' => 'freebies', 'order' => 6, 'visible' => true],
            ['label' => $t('ابدأ مشروعك', 'Start'), 'anchor' => 'contact', 'order' => 7, 'visible' => true],
        ],
        'hero' => [
            'eyebrow' => $t('تسويق رقمي وتحليل بيانات', 'Digital marketing and data analysis'),
            'title' => $t('نمو رقمي مبني على بيانات واضحة', 'Digital growth built on clear data'),
            'description' => $t(
                'أنا أمل العيسى، أساعد الشركات والمتاجر على تحويل التسويق والبيانات إلى قرارات نمو قابلة للقياس، بخبرة تتجاوز 8 سنوات وميزانيات إعلانية مُدارة بأكثر من 18 مليون ريال.',
                'I am Amal Aleissa. I help companies and stores turn marketing data into measurable growth decisions, with 8+ years of experience and SAR 18M+ in managed ad budgets.'
            ),
            'primary_button' => $t('احجز استشارتك', 'Book your consultation'),
            'secondary_button' => $t('مشاهدة الأعمال', 'View the work'),
            'primary_anchor' => 'contact',
            'secondary_anchor' => 'work',
            'words' => ['Data Analysis', 'Google Ads', 'Meta Ads', 'TikTok Ads', 'Snapchat Ads', 'SEO', 'Content Strategy', 'B2B', 'B2C', 'E-commerce', 'Growth', 'AI Tools'],
        ],
        'platforms' => [
            ['name' => 'Meta Business', 'url' => 'https://www.facebook.com/business/', 'icon' => 'fa-brands fa-meta', 'order' => 1, 'visible' => true],
            ['name' => 'Google Ads', 'url' => 'https://ads.google.com/', 'icon' => 'fa-brands fa-google', 'order' => 2, 'visible' => true],
            ['name' => 'Google Analytics', 'url' => 'https://analytics.google.com/', 'icon' => 'fa-solid fa-chart-column', 'order' => 3, 'visible' => true],
            ['name' => 'Google Search Console', 'url' => 'https://search.google.com/search-console', 'icon' => 'fa-solid fa-magnifying-glass-chart', 'order' => 4, 'visible' => true],
            ['name' => 'TikTok Business', 'url' => 'https://www.tiktok.com/business/', 'icon' => 'fa-brands fa-tiktok', 'order' => 5, 'visible' => true],
            ['name' => 'Snapchat Ads', 'url' => 'https://forbusiness.snapchat.com/', 'icon' => 'fa-brands fa-snapchat', 'order' => 6, 'visible' => true],
            ['name' => 'AI Tools', 'url' => '#expertise', 'icon' => 'fa-solid fa-robot', 'order' => 7, 'visible' => true],
        ],
        'stats' => [
            ['value' => '8', 'suffix' => '+', 'label' => $t('سنوات خبرة عملية', 'Years of practical experience'), 'icon' => 'fa-solid fa-award', 'order' => 1, 'visible' => true],
            ['value' => '18', 'suffix' => 'M+', 'label' => $t('ريال ميزانيات إعلانية مُدارة', 'SAR managed in ad budgets'), 'icon' => 'fa-solid fa-chart-line', 'order' => 2, 'visible' => true],
            ['value' => '43', 'suffix' => '+', 'label' => $t('متجر إلكتروني', 'E-commerce stores'), 'icon' => 'fa-solid fa-store', 'order' => 3, 'visible' => true],
            ['value' => '24', 'suffix' => 'M+', 'label' => $t('مشاهدة عضوية عبر المحتوى الرقمي', 'Organic content views'), 'icon' => 'fa-solid fa-eye', 'order' => 4, 'visible' => true],
        ],
        'headings' => [
            'why' => ['kicker' => $t('لماذا أمل العيسى؟', 'Why Amal Aleissa?'), 'title' => $t('خبرة عملية تقرأ الأرقام قبل إطلاق الحملات', 'Practical experience that reads the numbers before campaigns launch'), 'intro' => $t('مزيج من التسويق الرقمي، التجارة الإلكترونية، وتحليل البيانات يساعد المشاريع على اتخاذ قرارات نمو واضحة وقابلة للقياس.', 'A mix of digital marketing, e-commerce, and data analysis that helps projects make clear and measurable growth decisions.'), 'visible' => true],
            'services' => ['kicker' => $t('الخدمات', 'Services'), 'title' => $t('حلول تسويقية من الاستراتيجية إلى التنفيذ', 'Marketing solutions from strategy to execution'), 'intro' => $t('خدمات تساعد الشركات والمتاجر على النمو، تحسين الأداء، وبناء حضور رقمي احترافي مدعوم بالبيانات.', 'Services that help companies and stores grow, improve performance, and build a professional data-backed digital presence.'), 'visible' => true],
            'work' => ['kicker' => $t('نتائج الأعمال', 'Business results'), 'title' => $t('مشاريع وحملات حققت أثرًا واضحًا', 'Projects and campaigns with clear impact'), 'intro' => $t('ملخصات مركزة لأعمال التسويق والنمو، مع أرقام وصور توضّح الأثر بدون إطالة.', 'Focused summaries of marketing and growth work, with numbers and visuals that show the impact clearly.'), 'visible' => true],
            'stores' => ['kicker' => $t('إنشاء متاجر إلكترونية', 'E-commerce builds'), 'title' => $t('أكثر من مجرد متجر... تجربة شراء متكاملة', 'More than a store: a complete shopping experience'), 'intro' => $t('تجربة شراء احترافية، صفحات منتجات فعالة، تصميم يدعم المبيعات، وجاهزية للحملات الإعلانية.', 'Professional purchase journeys, effective product pages, sales-focused design, and campaign-ready storefronts.'), 'visible' => true],
            'social' => ['kicker' => $t('السوشال ميديا', 'Social media'), 'title' => $t('محتوى يعكس هوية العلامة ويعزز حضورها الرقمي', 'Content that reflects the brand and grows its digital presence'), 'intro' => $t('أساعد العلامات التجارية على بناء حضور رقمي احترافي من خلال محتوى يعكس هويتها ويعزز التواصل مع الجمهور. أكثر من 24 مليون مشاهدة حقيقية عبر محتوى متنوع للمشاريع.', 'I help brands build a professional digital presence through content that reflects their identity and supports marketing goals, with 24M+ real views across diverse projects.'), 'visible' => true],
            'clients' => ['kicker' => $t('كلمات العملاء', 'Client words'), 'title' => $t('كلمات العملاء هي أفضل شهادة', 'Client words are the strongest proof'), 'intro' => $t('صور من آراء العملاء وتسجيلات صوتية توثق التجربة والنتائج.', 'Client messages and audio recordings that document the experience and results.'), 'visible' => true],
            'logos' => ['kicker' => $t('علامات تجارية وثقت بخبرتي', 'Brands that trusted my expertise'), 'title' => $t('شراكات ومشاريع في مجالات متعددة', 'Partnerships and projects across diverse sectors'), 'intro' => $t('علامات تجارية ساهمت معها في تحقيق أهداف تسويقية مختلفة من بناء الحضور الرقمي إلى إدارة الحملات وتحقيق النمو.', 'Brands I supported across digital presence, campaign management, and growth goals.'), 'visible' => true],
            'freebies' => ['kicker' => $t('موارد مجانية', 'Free resources'), 'title' => $t('ملفات مجانية للمسوقين وأصحاب الأعمال', 'Free resources for marketers and business owners'), 'intro' => $t('ملفات وقوالب تساعدك على تنظيم العمل التسويقي، تحليل الأداء، واتخاذ قرارات مبنية على البيانات.', 'Templates that help organize marketing work, analyze performance, and make data-driven decisions.'), 'visible' => true],
            'blog' => ['kicker' => $t('المدونة', 'Blog'), 'title' => $t('سواليف الداتا والتسويق', 'Data and marketing talks'), 'intro' => $t('أفكار عملية عن السوق، الحملات، والبيانات تساعدك تقرأ مشروعك بوضوح أكبر.', 'Practical thoughts on markets, campaigns, and data to help you read your project more clearly.'), 'visible' => true],
        ],
        'why' => [
            ['title' => $t('خبرة تتجاوز 8 سنوات', '8+ years of experience'), 'description' => $t('خبرة عملية في السوق السعودي ومشاريع داخل المملكة وخارجها.', 'Practical experience in the Saudi market and projects inside and outside the Kingdom.'), 'icon' => 'fa-solid fa-award', 'order' => 1, 'visible' => true],
            ['title' => $t('إدارة ميزانيات كبيرة', 'Large budget management'), 'description' => $t('إدارة أكثر من 18 مليون ريال من الميزانيات الإعلانية.', 'Managing over SAR 18M in advertising budgets.'), 'icon' => 'fa-solid fa-sack-dollar', 'order' => 2, 'visible' => true],
            ['title' => $t('خبرة B2B و B2C', 'B2B and B2C expertise'), 'description' => $t('فهم مختلف لمسارات القرار، الجمهور، وقنوات النمو في كل نموذج.', 'Understanding decision paths, audiences, and growth channels across both models.'), 'icon' => 'fa-solid fa-people-arrows', 'order' => 3, 'visible' => true],
            ['title' => $t('43+ متجر إلكتروني', '43+ e-commerce stores'), 'description' => $t('بناء وإدارة متاجر إلكترونية بتجارب شراء واضحة وقابلة للنمو.', 'Building and managing stores with clear, scalable shopping experiences.'), 'icon' => 'fa-solid fa-store', 'order' => 4, 'visible' => true],
            ['title' => $t('تسويق وتحليل بيانات', 'Marketing and data analysis'), 'description' => $t('تحويل البيانات إلى قرارات تسويقية قابلة للقياس والتنفيذ.', 'Turning data into measurable and actionable marketing decisions.'), 'icon' => 'fa-solid fa-chart-pie', 'order' => 5, 'visible' => true],
            ['title' => $t('استراتيجيات نمو', 'Growth strategies'), 'description' => $t('تطوير استراتيجيات مبنية على الأرقام والنتائج، لا على التخمين.', 'Developing strategies built on numbers and results, not guesses.'), 'icon' => 'fa-solid fa-seedling', 'order' => 6, 'visible' => true],
            ['title' => $t('قيادة فرق ومشاريع', 'Team and project leadership'), 'description' => $t('قيادة وإدارة مشاريع وفرق تسويقية متكاملة من التخطيط حتى التنفيذ.', 'Leading integrated marketing teams and projects from planning to execution.'), 'icon' => 'fa-solid fa-diagram-project', 'order' => 7, 'visible' => true],
        ],
        'expertise' => [
            'visible' => true,
            'kicker' => $t('خبرتي', 'My expertise'),
            'title' => $t('تسويق يفهم الأرقام قبل الحملة', 'Marketing that understands the numbers before the campaign'),
            'description' => $t('أجمع بين الخبرة العملية في التسويق الرقمي، التجارة الإلكترونية، وماجستير تحليل البيانات لصناعة قرارات نمو واضحة وليست مبنية على التخمين.', 'I combine digital marketing experience, e-commerce knowledge, and a master’s in data analysis to shape clear growth decisions instead of guesses.'),
            'cards' => [
                ['value' => '8+', 'label' => $t('سنوات خبرة', 'Years'), 'description' => $t('تجربة عملية في السوق السعودي ومشاريع متنوعة.', 'Practical experience across Saudi and diverse projects.'), 'icon' => 'fa-solid fa-award'],
                ['value' => '18M+', 'label' => $t('ميزانيات مُدارة', 'Managed spend'), 'description' => $t('قراءة الأداء وتحسين الميزانيات بناءً على الأرقام.', 'Reading performance and optimizing budgets through data.'), 'icon' => 'fa-solid fa-chart-line'],
                ['value' => '43+', 'label' => $t('متجر إلكتروني', 'Stores'), 'description' => $t('خبرة في بناء متاجر وتجارب شراء قابلة للنمو.', 'Experience building scalable store experiences.'), 'icon' => 'fa-solid fa-store'],
            ],
            'tools' => [
                ['name' => 'Meta Business', 'icon' => 'fa-brands fa-meta'],
                ['name' => 'Google Ads', 'icon' => 'fa-brands fa-google'],
                ['name' => 'Google Analytics', 'icon' => 'fa-solid fa-chart-column'],
                ['name' => 'Search Console', 'icon' => 'fa-solid fa-magnifying-glass-chart'],
                ['name' => 'TikTok Business', 'icon' => 'fa-brands fa-tiktok'],
                ['name' => 'Snapchat Ads', 'icon' => 'fa-brands fa-snapchat'],
                ['name' => 'AI Tools', 'icon' => 'fa-solid fa-robot'],
            ],
        ],
        'services' => [
            ['title' => $t('استراتيجيات التسويق والنمو', 'Marketing and growth strategies'), 'description' => $t('بناء استراتيجيات تسويقية مدروسة تساعد الشركات على تحقيق النمو وزيادة المبيعات وتعزيز حضورها في السوق.', 'Building thoughtful marketing strategies that help companies grow, increase sales, and strengthen market presence.'), 'icon' => 'fa-solid fa-chart-line', 'order' => 1, 'visible' => true],
            ['title' => $t('إدارة وتحسين الحملات الإعلانية', 'Ad campaign management and optimization'), 'description' => $t('تخطيط وإدارة وتحسين الحملات الإعلانية لتحقيق أفضل النتائج وزيادة العائد على الاستثمار.', 'Planning, managing, and optimizing ad campaigns to improve results and return on investment.'), 'icon' => 'fa-solid fa-bullseye', 'order' => 2, 'visible' => true],
            ['title' => $t('التحول الرقمي للمشاريع', 'Digital transformation for projects'), 'description' => $t('مساعدة الشركات على تطوير عملياتها وحضورها الرقمي من خلال تطبيق الحلول والأدوات الرقمية المناسبة.', 'Helping companies develop operations and digital presence through the right tools and solutions.'), 'icon' => 'fa-solid fa-rocket', 'order' => 3, 'visible' => true],
            ['title' => $t('إنشاء وإدارة المتاجر الإلكترونية', 'E-commerce creation and management'), 'description' => $t('إنشاء وإطلاق المتاجر الإلكترونية وإدارتها وتطويرها لتحقيق تجربة تسوق فعالة ونمو مستدام.', 'Creating, launching, managing, and improving e-commerce stores for effective shopping experiences and sustainable growth.'), 'icon' => 'fa-solid fa-cart-shopping', 'order' => 4, 'visible' => true],
            ['title' => $t('تحسين محركات البحث واستراتيجية المحتوى', 'SEO and content strategy'), 'description' => $t('تطوير استراتيجيات المحتوى وتحسين الظهور في نتائج البحث لزيادة الوصول والعملاء المحتملين.', 'Developing content strategies and search visibility to increase reach and qualified leads.'), 'icon' => 'fa-solid fa-magnifying-glass', 'order' => 5, 'visible' => true],
            ['title' => $t('إدارة منصات التواصل الاجتماعي', 'Social media management'), 'description' => $t('إدارة الحسابات الاجتماعية وصناعة المحتوى الذي يعزز حضور العلامة التجارية ويزيد التفاعل.', 'Managing social accounts and creating content that strengthens brand presence and engagement.'), 'icon' => 'fa-solid fa-mobile-screen-button', 'order' => 6, 'visible' => true],
            ['title' => $t('تحليل البيانات والتقارير التسويقية', 'Data analysis and marketing reports'), 'description' => $t('تحليل البيانات التسويقية وتحويلها إلى رؤى تساعد على اتخاذ قرارات أكثر دقة وفعالية.', 'Analyzing marketing data and turning it into insights for more accurate and effective decisions.'), 'icon' => 'fa-solid fa-chart-simple', 'order' => 7, 'visible' => true],
            ['title' => $t('الاستشارات التسويقية', 'Marketing consulting'), 'description' => $t('تقديم استشارات عملية تساعد على تشخيص التحديات ووضع خطط تسويقية قابلة للتنفيذ.', 'Practical consulting to diagnose challenges and create actionable marketing plans.'), 'icon' => 'fa-solid fa-lightbulb', 'order' => 8, 'visible' => true],
            ['title' => $t('التدريب وورش العمل', 'Training and workshops'), 'description' => $t('تقديم برامج تدريبية وورش عمل متخصصة في التسويق الرقمي والتجارة الإلكترونية وتحليل البيانات.', 'Training programs and workshops in digital marketing, e-commerce, and data analysis.'), 'icon' => 'fa-solid fa-graduation-cap', 'order' => 9, 'visible' => true],
            ['title' => $t('الذكاء الاصطناعي في التسويق وتحليل البيانات', 'AI in marketing and data analysis'), 'description' => $t('توظيف أدوات الذكاء الاصطناعي لتحسين الأداء التسويقي وأتمتة المهام واستخراج رؤى تدعم اتخاذ القرار.', 'Using AI tools to improve marketing performance, automate tasks, and extract decision-supporting insights.'), 'icon' => 'fa-solid fa-robot', 'order' => 10, 'visible' => true],
        ],
        'cases' => [
            [
                'title' => $t('Sleep Nice | شركة سليب نايس', 'Sleep Nice'),
                'subtitle' => $t('Head of Marketing & Brand Growth | مديرة قسم التسويق', 'Head of Marketing & Brand Growth'),
                'badge' => 'Head of Marketing',
                'description' => $t('إدارة نمو وتسويق لعلامة أثاث تمتلك أكثر من 15 فرعًا داخل وخارج المملكة.', 'Growth and marketing leadership for a furniture brand with 15+ branches.'),
                'achievements' => [
                    $t('قيادة استراتيجية التسويق والهوية عبر الحملات والمحتوى.', 'Led marketing and brand strategy across campaigns and content.'),
                    $t('تحسين أداء الإعلانات الرقمية ورفع جودة الاستهداف.', 'Improved digital ad performance and targeting quality.'),
                    $t('متابعة مؤشرات الأداء وتحويلها إلى قرارات تشغيلية.', 'Tracked KPIs and turned them into operating decisions.'),
                ],
                'challenge' => $t('رفع الوعي والزيارات مع الحفاظ على كفاءة الحملات.', 'Grow awareness and visits while keeping campaigns efficient.'),
                'solution' => $t('مزيج من الإعلانات المدفوعة، المحتوى، المؤثرين، وتحليل الأداء المستمر.', 'A mix of paid ads, content, influencers, and continuous performance analysis.'),
                'metrics' => [['value' => '37.7M+', 'label' => 'Impressions'], ['value' => '375K+', 'label' => 'Swipe Ups'], ['value' => '932K+', 'label' => 'Clicks'], ['value' => '15+', 'label' => $t('الفروع', 'Branches')]],
                'tags' => ['Google Ads', 'Snapchat Ads', 'Influencer Marketing', 'Social Media Management', 'SEO & Content Strategy'],
                'images' => [$media('المشاريع/8a1391e7-1e47-47c8-89b2-e56d1a313222.JPG'), $media('نتائج الحملات الاعلانية/Sleepnice(1).png'), $media('نتائج الحملات الاعلانية/سناب شات.png')],
                'order' => 1,
                'visible' => true,
            ],
            [
                'title' => $t('متجر دهليز للكتب', 'Dahleez Books Store'),
                'subtitle' => $t('Performance Marketing & E-commerce Growth', 'Performance Marketing & E-commerce Growth'),
                'badge' => 'Performance Marketing',
                'description' => $t('تحسين أداء متجر كتب إلكتروني وزيادة مبيعاته عبر الحملات والمحتوى.', 'Improving an online bookstore’s performance and sales through campaigns and content.'),
                'challenge' => $t('زيادة الطلبات مع تحسين كفاءة الإعلان.', 'Increase orders while improving ad efficiency.'),
                'solution' => $t('استهداف أدق، تحسين مستمر للحملات، وقراءة أسبوعية للنتائج.', 'Sharper targeting, continuous campaign optimization, and weekly result reviews.'),
                'metrics' => [['value' => '+747%', 'label' => $t('نمو بالمبيعات', 'Sales growth')], ['value' => '252K+', 'label' => $t('ريال مبيعات', 'SAR sales')], ['value' => '256', 'label' => $t('طلب', 'Orders')], ['value' => '675', 'label' => $t('ريال متوسط الطلب', 'SAR average order')]],
                'tags' => ['TikTok Ads', 'Meta Ads', 'Performance Marketing', 'E-commerce Growth', 'Data Analysis'],
                'images' => [$media('نتائج الحملات الاعلانية/حملات دهليز.png'), $media('نتائج الحملات الاعلانية/دهليز قبل.png'), $media('نتائج الحملات الاعلانية/دهليز بعد.png')],
                'image_captions' => [null, $t('قبل', 'Before'), $t('بعد', 'After')],
                'order' => 2,
                'visible' => true,
            ],
            [
                'title' => $t('متجر هديتي للهدايا والورد', 'Hadiyati Gifts & Flowers'),
                'subtitle' => $t('Performance Marketing & E-commerce Growth', 'Performance Marketing & E-commerce Growth'),
                'badge' => 'E-commerce Growth',
                'description' => $t('نمو مبيعات متجر هدايا وورد من خلال تحسين الحملات ورحلة الشراء.', 'Growing a gifts and flowers store by improving campaigns and the purchase journey.'),
                'challenge' => $t('رفع المبيعات ومتوسط الطلب.', 'Raise sales and average order value.'),
                'solution' => $t('تحسين الاستهداف والإعلانات مع تبسيط رحلة الشراء.', 'Improved targeting and ads while simplifying the buying journey.'),
                'metrics' => [['value' => '+350%', 'label' => $t('نمو بالمبيعات', 'Sales growth')], ['value' => '110K+', 'label' => $t('ريال مبيعات', 'SAR sales')], ['value' => '277', 'label' => $t('طلب', 'Orders')], ['value' => '394', 'label' => $t('ريال متوسط الطلب', 'SAR average order')]],
                'tags' => ['TikTok Ads', 'Google Ads', 'E-commerce Growth', 'Performance Analysis'],
                'images' => [$media('نتائج الحملات الاعلانية/حملة الورد.png'), $media('نتائج الحملات الاعلانية/الورد قبل.png'), $media('نتائج الحملات الاعلانية/الورد بعد.png')],
                'image_captions' => [null, $t('قبل', 'Before'), $t('بعد', 'After')],
                'order' => 3,
                'visible' => true,
            ],
            [
                'title' => $t('Nova by Riyadh Safari', 'Nova by Riyadh Safari'),
                'subtitle' => $t('إدارة حملة إعلانية عالمية لعدة دول', 'Global Digital Marketing & Advertising Campaign Management'),
                'badge' => 'Global Campaign',
                'description' => $t('إدارة حملة عالمية لمسابقة فنون ونحت ضمن مشروع نوفا في سفاري الرياض.', 'Managing a global campaign for an art and sculpture competition under Nova by Riyadh Safari.'),
                'achievements' => [
                    $t('تنفيذ حملات إعلانية استهدفت جمهورًا دوليًا متعدد الأسواق.', 'Executed campaigns targeting international audiences across multiple markets.'),
                    $t('دعم استقطاب المشاركين المهتمين بالفنون والنحت من عدة دول.', 'Supported participant acquisition from multiple countries.'),
                    $t('تعزيز الحضور الرقمي للمشروع عبر القنوات الرقمية المختلفة.', 'Strengthened the project’s digital presence across channels.'),
                ],
                'challenge' => $t('الوصول لجمهور دولي مهتم بالفنون.', 'Reach an international art-focused audience.'),
                'solution' => $t('استهداف أسواق متعددة عبر Meta مع مراقبة الأداء حسب الدولة.', 'Multi-market Meta targeting with country-level performance monitoring.'),
                'metrics' => [['value' => 'Global', 'label' => 'Campaign'], ['value' => 'Multi', 'label' => 'Country Targeting'], ['value' => 'Art', 'label' => 'International Competition']],
                'tags' => ['Global Campaign Management', 'Audience Targeting', 'Campaign Optimization'],
                'images' => [$media('المشاريع/nova-riyadh-safari-1.jpg'), $media('المشاريع/nova-riyadh-safari-2.jpg'), $media('المشاريع/nova-riyadh-safari-3.jpg'), $media('المشاريع/نوفا.png')],
                'order' => 4,
                'visible' => true,
            ],
            [
                'title' => $t('SureFanni App | تطبيق شورفني', 'SureFanni App'),
                'subtitle' => $t('Performance Marketing & Growth Strategy', 'Performance Marketing & Growth Strategy'),
                'badge' => 'Growth Strategy',
                'description' => $t('تطوير وتنفيذ استراتيجية نمو لتطبيق خدمي عبر الحملات والمحتوى الإعلاني.', 'Developing and executing a growth strategy for a service app through campaigns and ad content.'),
                'achievements' => [
                    $t('إدارة وتنفيذ الحملات الإعلانية الرقمية وتحسين أدائها لتحقيق أهداف النمو.', 'Managed and optimized digital campaigns for growth goals.'),
                    $t('تطوير أفكار تسويقية ساهمت في زيادة الوعي بالتطبيق وتعزيز انتشاره.', 'Developed marketing ideas that increased awareness and reach.'),
                    $t('الوصول إلى المرتبة الأولى في فئة التطبيقات الخدمية على متجر التطبيقات خلال أسبوع من إطلاق الحملات.', 'Reached first place in the service app category within one week of campaign launch.'),
                ],
                'challenge' => $t('زيادة تحميلات التطبيق وتعزيز انتشاره في السوق خلال فترة قصيرة.', 'Increase app downloads and market reach in a short period.'),
                'solution' => $t('حملات مركزة وتصاميم إعلانية موجهة لزيادة التحميلات بسرعة.', 'Focused campaigns and ad creatives aimed at fast download growth.'),
                'metrics' => [['value' => '#1', 'label' => 'Top Ranking'], ['value' => $t('أسبوع', 'One week'), 'label' => $t('للوصول إلى القمة', 'To reach the top')], ['value' => 'B2B/B2C', 'label' => 'Growth Support']],
                'tags' => ['Growth Strategy', 'Ad Campaign Management', 'Creative Direction', 'B2B & B2C Marketing'],
                'images' => [$media('نتائج الحملات الاعلانية/تطبيق شورفني.jpg'), $media('لوقو العملاء/Sure-Fanni-Logo-side-1 (1).png')],
                'order' => 5,
                'visible' => true,
            ],
            [
                'title' => $t('Zaaer | زائر', 'Zaaer'),
                'subtitle' => $t('Digital Marketing & Content Management', 'Digital Marketing & Content Management'),
                'badge' => 'Content Management',
                'description' => $t('تطبيق متخصص في حلول الضيافة الفندقية.', 'An app specialized in hotel hospitality solutions.'),
                'challenge' => $t('زيادة الوعي بالتطبيق وتعزيز حضوره الرقمي في قطاع الضيافة.', 'Increase app awareness and strengthen digital presence in hospitality.'),
                'solution' => $t('إدارة المحتوى ومنصات التواصل الاجتماعي وتنفيذ الحملات الإعلانية الموجهة.', 'Managed content, social channels, and targeted digital campaigns.'),
                'metrics' => [['value' => 'Digital', 'label' => 'Presence Growth'], ['value' => 'Brand', 'label' => 'Awareness Campaigns'], ['value' => 'KPI', 'label' => 'Performance Tracking']],
                'tags' => ['Social Media Management', 'Content Marketing', 'Brand Awareness'],
                'images' => [$media('لوقو العملاء/زائر.svg')],
                'order' => 6,
                'visible' => true,
            ],
            [
                'title' => $t('نعناع', 'Naanah'),
                'subtitle' => $t('Digital Marketing & Customer Experience', 'Digital Marketing & Customer Experience'),
                'badge' => 'Customer Experience',
                'description' => $t('من أوائل المشاريع التي عملت عليها في مجال التسويق الرقمي.', 'One of the earliest projects I worked on in digital marketing.'),
                'challenge' => $t('تحسين تجربة العميل وفهم سلوك المستخدم وتحليل المنافسين.', 'Improve customer experience, understand user behavior, and analyze competitors.'),
                'solution' => $t('تنفيذ اختبارات تجربة العميل، تحليل رحلة المستخدم، ومقارنة الأداء مع المنافسين من خلال أسلوب المتسوق الخفي.', 'Ran customer experience tests, analyzed user journeys, and benchmarked competitors through mystery shopping.'),
                'metrics' => [['value' => 'CX', 'label' => 'Journey Analysis'], ['value' => 'Benchmark', 'label' => 'Competitor Analysis'], ['value' => 'Mystery', 'label' => 'Shopping']],
                'tags' => ['Social Media Management', 'Content Marketing', 'Customer Experience Testing', 'Competitor Analysis', 'Mystery Shopping'],
                'images' => [$media('لوقو العملاء/نعناع.png')],
                'order' => 7,
                'visible' => true,
            ],
        ],
        'stores' => [
            ['title' => $t('سمّار', 'Smar'), 'category' => $t('مستلزمات الجلسات الشتوية والتخييم', 'Winter and camping supplies'), 'description' => $t('متجر متخصص في مستلزمات الجلسات الشتوية والتخييم.', 'A store specialized in winter gathering and camping supplies.'), 'url_label' => 'amal.showcase/store/smar', 'chips' => [$t('تجربة شراء احترافية', 'Professional shopping'), $t('تصميم يدعم المبيعات', 'Sales-focused design')], 'image' => $media('انشاء متاجر الكترونية/سمار.png'), 'order' => 1, 'visible' => true],
            ['title' => $t('فولاذ', 'Folaz'), 'category' => $t('مستلزمات البناء والتشييد', 'Construction supplies'), 'description' => $t('موقع إلكتروني متخصص في مستلزمات البناء والتشييد، مصمم لعرض المنتجات والمواصفات الفنية بشكل واضح.', 'An online store for construction supplies designed to present products and technical specifications clearly.'), 'url_label' => 'amal.showcase/store/folaz', 'chips' => [$t('عرض منتجات واضح', 'Clear product display'), $t('مواصفات فنية', 'Technical specs')], 'image' => $media('انشاء متاجر الكترونية/folaz.JPEG'), 'order' => 2, 'visible' => true],
            ['title' => $t('متاع', 'Mata'), 'category' => $t('الأثاث الخشبي', 'Wood furniture'), 'description' => $t('متجر إلكتروني للأثاث الخشبي يركز على إبراز جمال المنتجات وتفاصيلها من خلال تصميم أنيق.', 'A wood furniture store focused on showing product beauty and details through elegant design.'), 'url_label' => 'amal.showcase/store/mata', 'chips' => [$t('تصميم أنيق', 'Elegant design'), $t('تفاصيل المنتج', 'Product details')], 'image' => $media('انشاء متاجر الكترونية/متجر متاع.png'), 'order' => 3, 'visible' => true],
            ['title' => $t('عالطاير', 'Al Tayer'), 'category' => $t('العطور', 'Perfumes'), 'description' => $t('متجر إلكتروني متخصص في العطور، يعكس تجربة تسوق تناسب فخامة المنتجات وجودتها.', 'A perfume store with a shopping experience that reflects product quality and premium positioning.'), 'url_label' => 'amal.showcase/store/altayer', 'chips' => [$t('هوية فاخرة', 'Premium identity'), $t('تجربة جوال', 'Mobile experience')], 'image' => $media('انشاء متاجر الكترونية/متجر عالطاير.png'), 'order' => 4, 'visible' => true],
            ['title' => 'NEE', 'category' => $t('التجميل والعناية', 'Beauty and care'), 'description' => $t('علامة تجارية متخصصة في منتجات التجميل والعناية، مصمم ليعكس هوية البراند ويبرز المنتجات بطريقة عصرية.', 'A beauty and care brand experience designed to reflect identity and present products in a modern way.'), 'url_label' => 'amal.showcase/store/nee', 'chips' => [$t('هوية البراند', 'Brand identity'), $t('عرض عصري', 'Modern display')], 'image' => $media('انشاء متاجر الكترونية/متجر ميك اب.png'), 'order' => 5, 'visible' => true],
        ],
        'social' => array_map(static fn ($row) => ['image' => $media($row[0]), 'alt' => $t($row[1], $row[2]), 'order' => $row[3], 'visible' => true], [
            ['سوشال ميديا/Petcure.png', 'تصميم سوشال ميديا يعكس هوية العلامة', 'Social media content reflecting brand identity', 1],
            ['سوشال ميديا/Diggipacks.png', 'تصميم محتوى سوشال ميديا', 'Social media content design', 2],
            ['سوشال ميديا/Sleepnice.png', 'محتوى رقمي لسليب نايس', 'Digital content for Sleep Nice', 3],
            ['سوشال ميديا/كيد فيرست سوشال ميديا.png', 'محتوى كيد فيرست', 'Kid First content', 4],
            ['سوشال ميديا/نوفا ايفنت سوشال ميديا.png', 'محتوى نوفا إيفنت', 'Nova Event content', 5],
            ['سوشال ميديا/انشاء متجر NEE Makeup Milano.png', 'محتوى NEE Makeup Milano', 'NEE Makeup Milano content', 6],
            ['سوشال ميديا/1سوشال ميديا.png', 'نتائج سوشال ميديا 1', 'Social media result 1', 7],
            ['سوشال ميديا/2سوشال ميديا.png', 'نتائج سوشال ميديا 2', 'Social media result 2', 8],
            ['سوشال ميديا/3سوشال ميديا.png', 'نتائج سوشال ميديا 3', 'Social media result 3', 9],
        ]),
        'testimonials' => array_map(static fn ($file, $i) => ['image' => $media('اراء العملاء/'.$file), 'alt' => $t('رأي عميل', 'Client testimonial'), 'order' => $i + 1, 'visible' => true], ['IMG_9683.PNG', 'IMG_1884.PNG', 'IMG_1883.PNG', 'IMG_1688.PNG', 'IMG_1667.PNG', 'IMG_0970.PNG'], range(0, 5)),
        'audio' => array_map(static fn ($file, $i) => ['title' => $t('تسجيل صوتي لعميل '.str_pad((string) ($i + 1), 2, '0', STR_PAD_LEFT), 'Client audio '.str_pad((string) ($i + 1), 2, '0', STR_PAD_LEFT)), 'file' => $media('صوتيات/'.$file), 'order' => $i + 1, 'visible' => true], ['AUDIO-2026-05-28-21-41-08.m4a', 'AUDIO-2026-05-05-05-43-16.m4a', 'AUDIO-2026-04-30-13-37-50.m4a', 'AUDIO-2026-04-20-20-31-37.m4a', 'AUDIO-2026-03-22-00-03-50.m4a'], range(0, 4)),
        'logos' => array_map(static fn ($file, $i) => ['image' => $media('لوقو العملاء/'.$file), 'alt' => $t('شعار علامة تجارية وثقت بخبرة أمل العيسى', 'Brand logo'), 'order' => $i + 1, 'visible' => true], ['dail.png', '2000x2000.png', '1080 x 1920.png', '1.png', 'تصميم بدون عنوان.png', 'الشرهان للعود .jpeg', 'WhatsApp Image 2026-04-29 at 8.47.33 PM.jpeg', 'Sure-Fanni-Logo-side-1 (1).png', 'Profile.png', 'nee.png', 'final logo-3.png', 'final logo-01.jpeg', 'صفوة الجوف .png', 'سليب نايس.jpeg', 'سكر ولبن.jpeg', 'زائر.svg', 'مرايا.webp', 'كيد فيرست.jpeg', 'عشاق العطور.jpeg', 'نعناع.png', 'هدايا جدة.avif'], range(0, 20)),
        'freebies' => [
            ['key' => 'social-media', 'title' => $t('ملف تنظيم السوشال ميديا', 'Social media planner'), 'description' => $t('قالب يساعدك على تنظيم المحتوى وإدارة حسابات السوشال ميديا.', 'A template for organizing content and managing social media accounts.'), 'file' => 'freebies/social media.xlsx', 'icon' => 'fa-solid fa-table-cells-large', 'order' => 1, 'visible' => true],
            ['key' => 'google-ads', 'title' => $t('نموذج تحليل Google Ads', 'Google Ads analysis template'), 'description' => $t('نموذج عملي لتحليل بيانات الحملات الإعلانية واتخاذ قرارات مبنية على الأرقام.', 'A practical template for analyzing campaign data and making data-driven decisions.'), 'file' => 'freebies/Google Ads نموذج التحليل والبيانات.xlsx', 'icon' => 'fa-solid fa-chart-simple', 'order' => 2, 'visible' => true],
        ],
        'newsletter' => [
            'title' => $t('أدخل بريدك للحصول على الملفات المجانية', 'Enter your email to receive the free resources'),
            'description' => $t('أدخل بريدك الإلكتروني للحصول على الملفات والأدوات المجانية مباشرة.', 'Enter your email to get the free files and tools directly.'),
            'button' => $t('إرسال رابط التحميل', 'Send download link'),
        ],
        'blog' => [
            ['title' => $t('لماذا تفشل أغلب المتاجر الإلكترونية في أول سنة؟', 'Why do most e-commerce stores fail in the first year?'), 'description' => $t('الأخطاء التي تمنع المتاجر من الوصول إلى نمو مستدام.', 'Mistakes that stop stores from reaching sustainable growth.'), 'image' => $media('انشاء متاجر الكترونية/متجر متاع.png'), 'order' => 1, 'visible' => true],
            ['title' => $t('كيف تقرأ نتائج حملاتك الإعلانية بطريقة صحيحة؟', 'How do you read campaign results correctly?'), 'description' => $t('طريقة مبسطة لتحويل الأرقام إلى قرارات تحسين واضحة.', 'A simple way to turn numbers into clear optimization decisions.'), 'image' => $media('نتائج الحملات الاعلانية/جوجل انالتكس.png'), 'order' => 2, 'visible' => true],
            ['title' => $t('الذكاء الاصطناعي في التسويق: فرصة أم مجرد موجة مؤقتة؟', 'AI in marketing: opportunity or temporary wave?'), 'description' => $t('كيف تستخدم أدوات الذكاء الاصطناعي دون فقدان وضوح الاستراتيجية.', 'How to use AI tools without losing strategic clarity.'), 'image' => $media('سوشال ميديا/1سوشال ميديا.png'), 'order' => 3, 'visible' => true],
        ],
        'contact' => [
            'kicker' => $t('ابدأ مشروعك', 'Start your project'),
            'title' => $t('وقتك ثمين ومشروعك يستحق النجاح', 'Your time is valuable, and your project deserves success'),
            'description' => $t('شارك تفاصيل مشروعك لأساعدك في تحديد أفضل الحلول التسويقية المناسبة لك.', 'Share your project details so I can help identify the best marketing solutions for you.'),
            'button' => $t('احجز استشارتك الآن', 'Book your consultation now'),
            'services' => [$t('الحملات الإعلانية', 'Ad campaigns'), $t('التحول الرقمي للمشروع', 'Project digital transformation'), $t('إنشاء متجر إلكتروني', 'E-commerce store creation'), $t('إدارة منصات التواصل الاجتماعي', 'Social media management')],
            'links' => [
                ['label' => 'TikTok @amal.digital.tips', 'url' => 'https://www.tiktok.com/@amal.digital.tips', 'icon' => 'fa-brands fa-tiktok'],
                ['label' => 'LinkedIn @amal_aleissa', 'url' => 'https://www.linkedin.com/in/amal_aleissa', 'icon' => 'fa-brands fa-linkedin'],
                ['label' => 'Instagram @amal.digital.tips', 'url' => 'https://www.instagram.com/amal.digital.tips', 'icon' => 'fa-brands fa-instagram'],
                ['label' => 'YouTube @amal.digital.tips', 'url' => 'https://www.youtube.com/@amal.digital.tips', 'icon' => 'fa-brands fa-youtube'],
                ['label' => 'WhatsApp +966559353383', 'url' => 'https://wa.me/966559353383', 'icon' => 'fa-brands fa-whatsapp'],
                ['label' => $t('الرياض - المملكة العربية السعودية', 'Riyadh, Saudi Arabia'), 'url' => '#contact', 'icon' => 'fa-solid fa-location-dot'],
            ],
        ],
    ],
    'theme' => \App\Services\ThemeValidator::DEFAULTS,
    'seo' => [
        'title' => $t('أمل العيسى | تسويق رقمي وتحليل بيانات', 'Amal Aleissa | Digital Marketing and Data Analysis'),
        'description' => $t('أمل العيسى تساعد الشركات والمتاجر على النمو من خلال التسويق الرقمي، تحليل البيانات، الحملات الإعلانية، المتاجر الإلكترونية، وإدارة السوشال ميديا.', 'Amal Aleissa helps companies and stores grow through digital marketing, data analysis, advertising campaigns, e-commerce, and social media management.'),
        'keywords' => $t('أمل العيسى، تسويق رقمي، تحليل بيانات، حملات إعلانية، متاجر إلكترونية، سوشال ميديا', 'Amal Aleissa, digital marketing, data analysis, ad campaigns, e-commerce, social media'),
        'og_title' => $t('أمل العيسى | نمو مبني على التسويق والبيانات', 'Amal Aleissa | Growth built on marketing and data'),
        'og_description' => $t('خبرة تتجاوز 8 سنوات، أكثر من 18 مليون ريال ميزانيات إعلانية مُدارة، و43+ متجر إلكتروني.', '8+ years of experience, SAR 18M+ managed ad budgets, and 43+ e-commerce stores.'),
        'og_image' => $media('logo.webp'),
        'indexable' => true,
        'schema' => ['job_title' => $t('متخصصة في التسويق الرقمي وتحليل البيانات', 'Digital Marketing and Data Analysis Specialist'), 'service_area' => 'Saudi Arabia'],
    ],
];
