@extends('layouts.admin',['title'=>'المحتوى وSEO']) @section('content')
<div class="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p class="text-sm text-slate-500">المسودة رقم {{ $version->version }}. التعديلات لا تظهر للعامة قبل النشر.</p></div><div class="flex flex-wrap gap-2"><a class="admin-btn-secondary" target="_blank" href="{{ route('admin.preview',[$version,'ar']) }}">معاينة العربية</a><a class="admin-btn-secondary" target="_blank" href="{{ route('admin.preview',[$version,'en']) }}">Preview English</a><form method="post" action="{{ route('admin.content.publish') }}">@csrf<button class="admin-btn" onclick="return confirm('نشر هذه المسودة الآن؟')"><i class="fa-solid fa-cloud-arrow-up"></i>نشر</button></form></div></div>
<form method="post" action="{{ route('admin.content.update') }}" class="space-y-6">@csrf @method('PUT')
<section class="admin-card"><h2 class="mb-4 text-xl font-extrabold">محتوى الصفحة</h2><p class="mb-5 text-sm text-slate-500">افتح كل مجموعة لتحرير النصوص والعناصر. حقول الترتيب تحدد موقع العنصر، وخيار ظاهر يخفيه دون حذفه.</p><div class="space-y-4">@foreach($version->content as $key=>$value)@include('admin.partials.content-field',['key'=>$key,'value'=>$value,'prefix'=>'content'])@endforeach</div></section>
<section class="admin-card"><h2 class="mb-5 text-xl font-extrabold">ألوان الهوية الآمنة</h2><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">@foreach($themeDefaults as $key=>$default)<label><span class="admin-label">{{ str_replace('_',' ',$key) }}</span><div class="flex gap-2"><input class="h-11 w-14 rounded-lg border" type="color" value="{{ $version->theme[$key]??$default }}" oninput="this.nextElementSibling.value=this.value"><input class="admin-input" name="theme[{{ $key }}]" value="{{ $version->theme[$key]??$default }}" pattern="#[0-9A-Fa-f]{6}" required></div></label>@endforeach</div></section>
<section class="admin-card"><h2 class="mb-5 text-xl font-extrabold">تهيئة محركات البحث</h2><div class="space-y-4">@foreach($version->seo as $key=>$value)@if($key!=='indexable')@include('admin.partials.content-field',['key'=>$key,'value'=>$value,'prefix'=>'seo'])@endif @endforeach<label class="flex items-center gap-2"><input type="hidden" name="seo[indexable]" value="0"><input type="checkbox" name="seo[indexable]" value="1" @checked($version->seo['indexable']??true)><strong>السماح بأرشفة الصفحة</strong></label></div></section>
<div class="sticky bottom-4 flex justify-end"><button class="admin-btn px-8 shadow-xl"><i class="fa-solid fa-floppy-disk"></i>حفظ المسودة</button></div></form>
<section class="admin-card mt-6"><h2 class="mb-4 text-lg font-extrabold">سجل النسخ</h2><div class="flex flex-wrap gap-3">@foreach($pageModel->versions->sortByDesc('version') as $item)<div class="rounded-xl border p-3"><strong>نسخة {{ $item->version }}</strong><small class="mx-2 rounded bg-slate-100 px-2 py-1">{{ $item->status }}</small>@if($item->id!==$version->id)<form class="mt-2" method="post" action="{{ route('admin.content.restore',$item) }}">@csrf<button class="text-sm font-bold text-emerald-700">استعادة إلى المسودة</button></form>@endif</div>@endforeach</div></section>
@endsection
